package ecommerce.main;
import java.util.List;

import ecommerce.com.Product;
import ecommerce.com.businesslogic.Service;
public class Main {
	public static void main(String args[]) {
		
		//id automaticllay generated by hibernte engine
		
		Service serve = new Service();
	Product newproducts = new Product();
		
		newproducts.setColor("silver");
		newproducts.setLaptopName("HP Pavilion");
		newproducts.setModel("RG16878RE");
		newproducts.setScreensize("17 inches");
		newproducts.setWeight("1.8 Kg");
		
		serve.addProduct(newproducts);
		
	//	Product updateProduct = new Product();
	//.setColor("Bluish Silver");
	//	updateProduct.setLaptopName("HP Pavilion");
	//	updateProduct.setModel("UGIT786FG");
	//	updateProduct.setScreensize("13 inches");
	//	updateProduct.setWeight("1.85 Kg");
		//list of products
		
		//List<Product> listofprod =serve.getProductDetails();
		
		
	//	Product updated = serve.updateEmployeById(updateProduct, 3);
	//	String laptopNameNow = updated.getLaptopName();
	//	System.out.println("Now the LaptopName is: " + laptopNameNow);
	//.out.println("Operation successful!!");
	}

}
